# Generated by Django 2.1.2 on 2018-10-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181026_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='images/')),
                ('pic_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
