# Generated by Django 2.1.2 on 2018-11-09 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181026_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='author',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
