# Generated by Django 2.1.2 on 2018-11-09 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_upload_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='author',
            field=models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL),
        ),
    ]
