# Generated by Django 2.1.2 on 2018-11-09 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181109_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='author',
            field=models.ForeignKey(null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL),
        ),
    ]
