# Generated by Django 2.1.2 on 2018-11-09 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20181109_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='timestamp',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
