# Generated by Django 2.1.2 on 2019-05-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='config',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='editor',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
