# Generated by Django 2.2 on 2019-06-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190601_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
